[package]
name = "image"
version = "0.2.0"
license = "MIT"
description = "Imaging library written in Rust. Provides basic filters and decoders for the most common image formats."
authors = [
    "ccgn",
    "bvssvni <bvssvni@gmail.com>",
    "nwin",
    "TyOverby <ty@pre-alpha.com>"]
readme = "README.md"
documentation = "http://www.piston.rs/image/image/index.html"
repository = "https://github.com/PistonDevelopers/image.git"
homepage = "https://github.com/PistonDevelopers/image"
exclude = [
    "src/png/testdata/*",
    "examples/*",
    "tests/*",
]
[lib]
name = "image"
path = "./src/lib.rs"

[dependencies.num]
version = "0.1.15"

[dev-dependencies.glob]
version = "0.2.3"
